### ISSUE TITLE
Can not enter the training stage

### ISSUE THREAD

**Issue by mk123qwe** [Maple728/MTNet#1]
I can't get into training by running code.
The code will stop at run_one_epoch(sess, model, train_batch_data, ds_handler, i, True) , but it will not report errors.

**Comment by Maple728** [comment]
It works fine if no errors are thrown. The model training is very slow because the encoders cost a lot time. I train one epoch and it takes an hour on 1080Ti.

**Comment by mk123qwe** [comment]
> It works fine if no errors are thrown. The model training is very slow because the encoders cost a lot time. I train one epoch and it takes an hour on 1080Ti.
