### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by z744364418p** [Maple728/MTNet#4]
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value mae_metric/count

rmse_loss, _= tf.metrics.root_mean_squared_error(Y, y_pred, updates_collections = 'summary_ops', name = 'mae_metric')

**Comment by Maple728** [comment]
I'm sorry to have replied to you so long. You can comment out this line of code without affecting the training and prediction of the model
