### ISSUE TITLE
input_keep_prob and output_keep_prob is not set to 1 during prediction 

### ISSUE THREAD

**Issue by shanyu-sys** [Maple728/MTNet#5]
As I notice that you always use `self.config.input_keep_prob` while building model. And the placeholder of `input_keep_prob` and `output_keep_prob` is not used. It behaves the same during training but in prediction, the value of 1 you passed into the two placeholders doesn't have any effect. This means your prediction results vary every time and your evaluation results can not be reproduced. 

https://github.com/Maple728/MTNet/blob/master/models/MTNet.py#L133-L137

**Comment by Maple728** [comment]
Thanks, you are right. I‘ll correct this mistake later.

**Comment by hliuw** [comment]
the code here 
https://github.com/Maple728/MTNet/blob/b0d011872b4900b6b965bea0b93d33ca67d91169/models/MTNet.py#L126
concerning the same issue is not changed yet

**Comment by Maple728** [comment]
Thank you for pointing out the mistake. I have solved this issue.
